// Copyright 2023 Tencent Inc.
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_angel_fl_crypto_heu_HeuJNI */

#ifndef _Included_com_tencent_angel_fl_crypto_heu_HeuJNI
#define _Included_com_tencent_angel_fl_crypto_heu_HeuJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    heKitCreate
 * Signature: (II[J)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_heKitCreate(
    JNIEnv *, jclass, jint, jint, jlongArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    heKitCreateFromKeys
 * Signature: ([B[B[J)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_heKitCreateFromKeys(
    JNIEnv *, jclass, jbyteArray, jbyteArray, jlongArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    heKitFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_heKitFree(JNIEnv *, jclass, jlong);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    destinationHeKitCreate
 * Signature: ([B[J)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_destinationHeKitCreate(JNIEnv *,
                                                                   jclass,
                                                                   jbyteArray,
                                                                   jlongArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    destinationHeKitFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_destinationHeKitFree(JNIEnv *,
                                                                 jclass, jlong);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    getPubKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_getPubKey(JNIEnv *, jclass, jlong);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    getSecKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_getSecKey(JNIEnv *, jclass, jlong);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    encrypt
 * Signature: (J[D[[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_encrypt(
    JNIEnv *, jclass, jlong, jdoubleArray, jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    encryptPair
 * Signature: (J[D[D[[B)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_encryptPair(
    JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray, jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    decrypt
 * Signature: (J[[B[D)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_decrypt(
    JNIEnv *, jclass, jlong, jobjectArray, jdoubleArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    decryptPair
 * Signature: (J[[B[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_decryptPair(
    JNIEnv *, jclass, jlong, jobjectArray, jdoubleArray, jdoubleArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    encrypt1
 * Signature: (JD)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_encrypt1(JNIEnv *, jclass, jlong,
                                                     jdouble);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    encryptPair1
 * Signature: (JDD)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_encryptPair1(JNIEnv *, jclass,
                                                         jlong, jdouble,
                                                         jdouble);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    decrypt1
 * Signature: (J[B)D
 */
JNIEXPORT jdouble JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_decrypt1(
    JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    decryptPair1
 * Signature: (J[B[D)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_angel_fl_crypto_heu_HeuJNI_decryptPair1(
    JNIEnv *, jclass, jlong, jbyteArray, jdoubleArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    dhekitEncrypt
 * Signature: (J[D[[B)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_dhekitEncrypt(JNIEnv *, jclass,
                                                          jlong, jdoubleArray,
                                                          jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    dhekitEncryptPair
 * Signature: (J[D[D[[B)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_dhekitEncryptPair(
    JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray, jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    dhekitEncrypt1
 * Signature: (JD)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_dhekitEncrypt1(JNIEnv *, jclass,
                                                           jlong, jdouble);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    dhekitEncryptPair1
 * Signature: (JDD)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_dhekitEncryptPair1(JNIEnv *, jclass,
                                                               jlong, jdouble,
                                                               jdouble);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    addCipher
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_addCipher(JNIEnv *, jclass, jlong,
                                                      jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    addCipherInplace
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_addCipherInplace(JNIEnv *, jclass,
                                                             jlong, jbyteArray,
                                                             jbyteArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    addCiphersInplace
 * Signature: (J[[B[[B)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_addCiphersInplace(JNIEnv *, jclass,
                                                              jlong,
                                                              jobjectArray,
                                                              jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    scatterAddCiphersInplace
 * Signature: (J[[B[[B[JZ)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_scatterAddCiphersInplace(
    JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jlongArray, jboolean);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    addCiphersInplaceAxis0
 * Signature: (J[[B[[[B)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_addCiphersInplaceAxis0(
    JNIEnv *, jclass, jlong, jobjectArray, jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    subCipher
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_subCipher(JNIEnv *, jclass, jlong,
                                                      jbyteArray, jbyteArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    subCipherInplace
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_subCipherInplace(JNIEnv *, jclass,
                                                             jlong, jbyteArray,
                                                             jbyteArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    subCiphersInplace
 * Signature: (J[[B[[B)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_subCiphersInplace(JNIEnv *, jclass,
                                                              jlong,
                                                              jobjectArray,
                                                              jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    scatterSubCiphersInplace
 * Signature: (J[[B[[B[JZ)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_scatterSubCiphersInplace(
    JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jlongArray, jboolean);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    subCiphersInplaceAxis0
 * Signature: (J[[B[[[B)I
 */
JNIEXPORT jint JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_subCiphersInplaceAxis0(
    JNIEnv *, jclass, jlong, jobjectArray, jobjectArray);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    multiPlain
 * Signature: (J[BD)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_multiPlain(JNIEnv *, jclass, jlong,
                                                       jbyteArray, jdouble);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    multiPlainInplace
 * Signature: (J[BD)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_multiPlainInplace(JNIEnv *, jclass,
                                                              jlong, jbyteArray,
                                                              jdouble);

/*
 * Class:     com_tencent_angel_fl_crypto_heu_HeuJNI
 * Method:    sumCiphers
 * Signature: (J[[BI)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_tencent_angel_fl_crypto_heu_HeuJNI_sumCiphers(JNIEnv *, jclass, jlong,
                                                       jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
